#ifndef SEQ_GLOBALS
#define SEQ_GLOBALS

#define SEQ_STAGES 8
#define SEQ_ROWS 3

#define REFRESH_VALUES_US 1000
#define REFRESH_SEVEN_SEGMENT_US 5000

#define ANALOG_CERTAINTY_TARGET 10

#define STAGE_NONE SEQ_STAGES + 1

#endif